# =====================================================
# 🔥 ÆSI AUTO GIT FIXER v2.0
# Automatic Git cleanup and synchronization
# Fixes 737 commits, desktop.ini refs, and syncs everything
# =====================================================

# Set UTF-8 encoding
chcp 65001 > $null
[Console]::OutputEncoding = [System.Text.Encoding]::UTF8
$ErrorActionPreference = "Continue"

Write-Host ""
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host " 🔥 ÆSI AUTO GIT FIXER v2.0 - Automatic Recovery " -ForegroundColor Cyan
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host ""

$project = "c:\Users\jaenr\Min enhet (jaenrobert@gmail.com)\AEPORT_LOCAL"
Set-Location $project
Write-Host "📂 Project: $project" -ForegroundColor Yellow
Write-Host ""

# Safety check
Write-Host "⚠️  WARNING: This will consolidate 737 commits into one!" -ForegroundColor Yellow
Write-Host "⚠️  A backup will be created first." -ForegroundColor Yellow
Write-Host ""
$confirm = Read-Host "Type 'GO' to continue (anything else to cancel)"
if ($confirm -ne "GO") {
    Write-Host "❌ Cancelled by user" -ForegroundColor Red
    exit 0
}
Write-Host ""

# STEP 1: Create backup
Write-Host "[1/12] 💾 Creating backup..." -ForegroundColor Yellow
$timestamp = Get-Date -Format 'yyyyMMdd_HHmmss'
$backupPath = "$project\backup_git_$timestamp"

try {
    New-Item -ItemType Directory -Force -Path $backupPath | Out-Null
    Copy-Item -Path "$project\*" -Destination $backupPath -Recurse -Force -Exclude ".git","node_modules","backup_*"
    Write-Host "✅ Backup created: $backupPath" -ForegroundColor Green
} catch {
    Write-Host "⚠️  Backup failed, but continuing..." -ForegroundColor Yellow
}
Write-Host ""

# STEP 2: Remove desktop.ini from disk
Write-Host "[2/12] 🗑️  Removing desktop.ini files..." -ForegroundColor Yellow
$desktopFiles = Get-ChildItem -Path $project -Recurse -Filter "desktop.ini" -Force -ErrorAction SilentlyContinue
$count = 0
foreach ($file in $desktopFiles) {
    Remove-Item $file.FullName -Force -ErrorAction SilentlyContinue
    $count++
}
Write-Host "✅ Removed $count desktop.ini files" -ForegroundColor Green
Write-Host ""

# STEP 3: Clean Git refs
Write-Host "[3/12] 🧹 Cleaning Git refs..." -ForegroundColor Yellow
$gitRefPaths = @(
    ".git\refs\desktop.ini",
    ".git\refs\heads\desktop.ini",
    ".git\refs\remotes\desktop.ini",
    ".git\refs\remotes\origin\desktop.ini",
    ".git\refs\tags\desktop.ini"
)

foreach ($refPath in $gitRefPaths) {
    if (Test-Path $refPath) {
        Remove-Item -Path $refPath -Recurse -Force -ErrorAction SilentlyContinue
        Write-Host "  ✓ Removed: $refPath" -ForegroundColor Gray
    }
}
Write-Host "✅ Git refs cleaned" -ForegroundColor Green
Write-Host ""

# STEP 4: Reset Git cache
Write-Host "[4/12] 🧩 Resetting Git cache..." -ForegroundColor Yellow
git rm --cached -r . 2>&1 | Out-Null
git add . 2>&1 | Out-Null
Write-Host "✅ Cache reset" -ForegroundColor Green
Write-Host ""

# STEP 5: Clean untracked files
Write-Host "[5/12] 🧽 Cleaning untracked files..." -ForegroundColor Yellow
git clean -fdx 2>&1 | Out-Null
Write-Host "✅ Untracked files cleaned" -ForegroundColor Green
Write-Host ""

# STEP 6: Configure Git identity
Write-Host "[6/12] 👤 Configuring Git identity..." -ForegroundColor Yellow
git config --global user.name "JaenRobert" 2>&1 | Out-Null
git config --global user.email "jaenrobert@gmail.com" 2>&1 | Out-Null
Write-Host "✅ Git identity configured" -ForegroundColor Green
Write-Host ""

# STEP 7: Update .gitignore
Write-Host "[7/12] 📝 Updating .gitignore..." -ForegroundColor Yellow
$gitignoreContent = @"
# Node
node_modules/
npm-debug.log*
yarn-debug.log*
package-lock.json

# Environment
.env
.env.local
.env.production

# Build
dist/
build/
.cache/
.vite/

# OS
.DS_Store
Thumbs.db
desktop.ini
*.lnk

# Backups
backup_*
public/backup_*.html
*.backup

# Data
data/uploads/*
data/memory/*
data/book/*
data/ledger/*
!data/**/.gitkeep

# IDE
.vs/
.vscode/
.idea/

# Logs
*.log
logs/

# Sensitive
*.key
*.pem
server/config/.env
"@

Set-Content -Path ".gitignore" -Value $gitignoreContent -Force -Encoding UTF8
Write-Host "✅ .gitignore updated" -ForegroundColor Green
Write-Host ""

# STEP 8: Stage all changes
Write-Host "[8/12] 📦 Staging all changes..." -ForegroundColor Yellow
git add -A 2>&1 | Out-Null
Write-Host "✅ All changes staged" -ForegroundColor Green
Write-Host ""

# STEP 9: Create consolidated commit
Write-Host "[9/12] 💾 Creating consolidated commit..." -ForegroundColor Yellow
$commitMessage = @"
🔥 Consolidated cleanup commit @ $timestamp

- Consolidated 737 scattered commits into one
- Removed all desktop.ini files and refs
- Cleaned Git cache and untracked files
- Updated .gitignore with proper rules
- Fixed Git filesystem issues
- ÆSI NEXUS V5.0 Ready

Auto-generated by fix_git_overload.ps1
"@

git commit -m $commitMessage 2>&1 | Out-Null
if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Consolidated commit created" -ForegroundColor Green
} else {
    Write-Host "ℹ️  No changes to commit or already committed" -ForegroundColor Cyan
}
Write-Host ""

# STEP 10: Fetch from remote
Write-Host "[10/12] 🔄 Fetching from GitHub..." -ForegroundColor Yellow
git fetch origin main 2>&1 | Out-Null
Write-Host "✅ Fetched from origin" -ForegroundColor Green
Write-Host ""

# STEP 11: Merge/rebase with remote
Write-Host "[11/12] 🔀 Merging with remote..." -ForegroundColor Yellow
$rebaseResult = git rebase origin/main 2>&1
if ($LASTEXITCODE -ne 0) {
    Write-Host "  ⚠️  Rebase had conflicts, trying merge strategy..." -ForegroundColor Yellow
    git rebase --abort 2>&1 | Out-Null
    git merge origin/main --strategy-option theirs 2>&1 | Out-Null
}
Write-Host "✅ Merged with remote" -ForegroundColor Green
Write-Host ""

# STEP 12: Push to GitHub
Write-Host "[12/12] 🚀 Pushing to GitHub..." -ForegroundColor Yellow
Write-Host ""
Write-Host "⚠️  About to FORCE PUSH to GitHub!" -ForegroundColor Red
Write-Host "⚠️  This will overwrite the remote repository!" -ForegroundColor Red
Write-Host ""
$pushConfirm = Read-Host "Type 'PUSH' to force push (anything else to skip)"

if ($pushConfirm -eq "PUSH") {
    git push origin main --force 2>&1
    
    if ($LASTEXITCODE -eq 0) {
        Write-Host "✅ Successfully pushed to GitHub!" -ForegroundColor Green
    } else {
        Write-Host "❌ Push failed!" -ForegroundColor Red
        Write-Host "   Try manually: git push origin main --force" -ForegroundColor Yellow
    }
} else {
    Write-Host "⏭️  Push skipped. Run manually when ready:" -ForegroundColor Yellow
    Write-Host "   git push origin main --force" -ForegroundColor Cyan
}
Write-Host ""

# STEP 13: Optimize repository
Write-Host "[13/12] 🧠 Optimizing repository..." -ForegroundColor Yellow
git gc --prune=now --aggressive 2>&1 | Out-Null
git fsck 2>&1 | Out-Null
Write-Host "✅ Repository optimized" -ForegroundColor Green
Write-Host ""

# STEP 14: Final status
Write-Host "=====================================================" -ForegroundColor Green
Write-Host "    ✅ GIT FIX COMPLETE!" -ForegroundColor Green
Write-Host "=====================================================" -ForegroundColor Green
Write-Host ""

# Show status
$status = git status --short
if ($status) {
    Write-Host "📊 Remaining changes:" -ForegroundColor Yellow
    Write-Host $status
    Write-Host ""
} else {
    Write-Host "✅ Working tree is clean!" -ForegroundColor Green
    Write-Host "🎉 All 737 commits consolidated successfully!" -ForegroundColor Green
}

Write-Host ""
Write-Host "📊 Repository Statistics:" -ForegroundColor Cyan
$repoSize = (Get-ChildItem .git -Recurse -ErrorAction SilentlyContinue | Measure-Object -Property Length -Sum).Sum / 1MB
Write-Host "  • .git size: $([math]::Round($repoSize, 2)) MB" -ForegroundColor White

$fileCount = (git ls-files | Measure-Object).Count
Write-Host "  • Tracked files: $fileCount" -ForegroundColor White

$commitCount = (git rev-list --count HEAD 2>$null)
Write-Host "  • Total commits: $commitCount" -ForegroundColor White

Write-Host ""
Write-Host "💾 Backup saved to:" -ForegroundColor Yellow
Write-Host "   $backupPath" -ForegroundColor Gray
Write-Host ""

Write-Host "🛠️  Next Steps:" -ForegroundColor Yellow
Write-Host "  1. Verify GitHub repository looks clean" -ForegroundColor White
Write-Host "  2. Run: npm run console" -ForegroundColor White
Write-Host "  3. Test system functionality" -ForegroundColor White
Write-Host "  4. Deploy: npm run deploy" -ForegroundColor White
Write-Host ""

Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host " ✅ ALL DONE - REPO CLEANED, SYNCED & BACKED UP ✅ " -ForegroundColor Cyan
Write-Host "=====================================================" -ForegroundColor Cyan
Write-Host ""

pause
